#delay: The delay before the item animation begins
#types: your crate types
#every type needs the following format, you can add as much as you want types, items and item enchantments
#for commands you can use the following formatting:
# - {player} for the player
# - {reward} for the reward
# - {crate} for the crate type
#The item change is the change to get that item from the crate
#   <type>:
#     name: <the text that appears above the created crates>
#     rewards:
#       - name: <reward_name>
#         item: - The item that appears above the crate
#           name: <item_name>
#           id: <item_id>
#           meta: <item_meta>
#           amount: <amount of the item>
#           lore: <custom item lore>
#         enchantments:
#           - name: <enchantment_name>
#             level: <echantment_level>
#         commands: - Commands that only executes with this reward
#           - <command>
#         change: <the change to get the item>
#     commands: - Commands that always executes when opening this crate
#       - <command>
#       - <second command>

delay: 1

types:
  common:
    name: §eCommon §6Crate
    rewards:
      - name: Rare diamond
        item:
          name: Diamond
          id: 388
          meta: 0
          amount: 1
          lore: Rare diamond
          enchantments:
            - name: efficiency
              level: 1
        commands:
          - msg {player} be carefull with this diamond!
        change: 1
      - name: Garbage
        item:
          name: Garbage
          id: 3
          meta: 1
          amount: 2
          lore: Pure Garbage
        commands:
          - say {player}, please dump your garbage!
        change: 10
    commands:
      - say {player} won {reward} from a {crate}
      - givemoney {player} 100